// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimationController from "./animation_controller"
application.register("animation", AnimationController)

import LandingController from "./landing_controller"
application.register("landing", LandingController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import MessagesController from "./messages_controller"
application.register("messages", MessagesController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NasaController from "./nasa_controller"
application.register("nasa", NasaController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import PaginationController from "./pagination_controller"
application.register("pagination", PaginationController)

import PostsController from "./posts_controller"
application.register("posts", PostsController)

import PostsFormController from "./posts_form_controller"
application.register("posts-form", PostsFormController)

import ReloadController from "./reload_controller"
application.register("reload", ReloadController)

import SessionController from "./session_controller"
application.register("session", SessionController)

import UsertabsController from "./usertabs_controller"
application.register("usertabs", UsertabsController)
